# Generated by Django 3.1 on 2020-08-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninjas',
            old_name='dojo_id',
            new_name='user_ninja',
        ),
        migrations.RemoveField(
            model_name='dojos',
            name='dojo_id',
        ),
        migrations.RemoveField(
            model_name='ninjas',
            name='ninja_id',
        ),
    ]
